# Generated by Django 5.2.1 on 2025-06-24 17:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_farm'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldBoundary',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('area_hectares', models.FloatField(blank=True, help_text='Size of the field in hectares', null=True)),
                ('soil_type', models.CharField(blank=True, max_length=100, null=True)),
                ('soil_texture', models.CharField(blank=True, max_length=100, null=True)),
                ('soil_ph', models.FloatField(blank=True, null=True)),
                ('organic_carbon', models.CharField(blank=True, max_length=100, null=True)),
                ('recommended_crops', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_boundaries', to='base.farm')),
            ],
            options={
                'verbose_name': 'Field Boundary',
                'verbose_name_plural': 'Field Boundaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
